# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ca42990f0e0819fe72a028cd3f7ae0b7cc19ace5141ad79373afde5280527df40f5bb40bef21b2f9ac7d2d4b43660a734eebe61fca7d35168ad1e5bbb6a2103

test:
  secret_key_base: 43df29f2125b5bdbd53671055e3b4485bbad7d39e95564087fa5b01e5c798945315645760ca011978e4b2f904f809a33887f9986ac42bb665ef5528a047a2d02

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
